# version: '3'

# services:

#   db:
#     image: mysql:8
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: 123456
#       MYSQL_DATABASE: db
#     ports:
#       - "3306:3306"

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - "8000:8080"

# #mysql://bauti:123456@localhost:3306/

